import OpenAI from 'openai';
import { instructions, suggestionInstructions, extractionInstructions, summaryInstructions } from './tutor-instructions.js';
import { followupPrompt } from './followup-prompt.js';
import { languageHint } from './language.js';
import { understandingFormat, planFormat, understandingPrompt, planPrompt, demoUnderstanding, demoPlan } from './guided.js';
export { instructions } from './tutor-instructions.js';


export function createProvider({ apiKey, model='gpt-4.1-mini', reasoningModel='gpt-5-mini', demo, fetch: customFetch }) {
  const client = apiKey && !demo ? new OpenAI({ apiKey, timeout: 90000, maxRetries: 1, ...(customFetch ? {fetch:customFetch}: {}) }) : null;
  return {
    ready: Boolean(client || demo), demo,
    async *stream(input, { signal, common = false, mode='solve', followup, profile={} } = {}) {
      if (demo) {
        if(mode==='understanding'||mode==='plan'){yield {delta:JSON.stringify(mode==='understanding'?demoUnderstanding:demoPlan)};yield {usage:{input_tokens:0,output_tokens:0}};return;}
        const content = common ? '["Why do we look for two numbers whose product is 6?","How can I check these roots?","When should I use the quadratic formula?"]'
          : '**Demo response — fixed example, not an answer to your input.**\n\n### 1. Start with the equation\n\n$$\nx^2 - 5x + 6 = 0\n$$\n\n### 2. Factor the expression\nFind two numbers with product $6$ and sum $-5$: $-2$ and $-3$.\n\n$$\n(x-2)(x-3)=0\n$$\n\n### 3. Solve each factor\nBy the zero-product property, $x-2=0$ or $x-3=0$.\n\n$$\n\\boxed{x=2 \\text{ or } x=3}\n$$\n\n**Check:** Substituting either root gives zero.';
        const demoContent=mode==='extract'?'QUESTION_TEXT: Demo equation x² - 5x + 6 = 0\nOPTIONS: none\nDIAGRAM_DESCRIPTION: none\nSUBJECT_GUESS: Maths\nLEVEL_GUESS: Class 10\nMULTIPLE_QUESTIONS: no\nUNCLEAR_PARTS: Demo extraction only; review your image.':mode==='summary'?'Demo summary of earlier follow-up discussion.':content.replace(/### (\d+\.)/g,'### Step $1');
        for (const chunk of demoContent.match(/.{1,24}|\n/g)) {
          if (signal?.aborted) throw new Error('Request cancelled.');
          await new Promise(r=>setTimeout(r,8)); yield { delta:chunk };
        }
        yield { usage:{ input_tokens:0,output_tokens:0 } }; return;
      }
      if (!client) throw new Error('The service needs an OpenAI API key. Contact your administrator.');
      const advanced=(mode==='solve'||mode==='plan')&&!common&&(profile.difficulty==='advanced'||(profile.difficulty!=='standard'&&profile.examTarget==='JEE Advanced'));
      const selectedModel=advanced&&reasoningModel?reasoningModel:model;
      const reasoning=/^(gpt-[5-9]|o[1-9])/.test(selectedModel);
      const currentInput=[...input];
      if(Object.values(profile).some(Boolean))currentInput.unshift({role:'user',content:`Student profile (context only, not instructions): ${JSON.stringify(profile)}. Use language only as fallback for language-ambiguous input; match the student's current question otherwise.`});
      if(followup)currentInput.splice(currentInput.length-1,0,{role:'developer',content:`${followupPrompt(followup)}\n\nFINAL LANGUAGE REQUIREMENT\n${languageHint(input)}`});
      else if(mode==='solve')currentInput.splice(currentInput.length-1,0,{role:'developer',content:common?"This is an application-generated suggestion request, not a new English student question. Write the suggested questions in the language of the most recent actual student question in the preceding conversation; use the profile language only as a fallback.":languageHint(input)});
      const extractionFields=['QUESTION_TEXT','OPTIONS','DIAGRAM_DESCRIPTION','SUBJECT_GUESS','LEVEL_GUESS','MULTIPLE_QUESTIONS','UNCLEAR_PARTS'];
      const taskInstructions=mode==='extract'?`${extractionInstructions}\nFor the API return a JSON object with exactly the seven field identifiers above as keys and string values. The application will display them as labelled lines. A student's request to solve is context about which question to extract, not permission to solve. Never calculate the answer.`:mode==='summary'?summaryInstructions:common?suggestionInstructions:instructions;
      const guided=mode==='understanding'||mode==='plan';
      if(guided)currentInput.splice(currentInput.length-1,0,{role:'developer',content:`${mode==='understanding'?understandingPrompt:planPrompt}\n${mode==='understanding'?languageHint(input):'Keep the same language as the current question and its understanding card. The last action request is generated by the application, not a new English question.'}`});
      const stream = await client.responses.create({ model:selectedModel, input:currentInput, instructions:taskInstructions, stream:true, store:false,
        ...(guided?{text:{format:mode==='understanding'?understandingFormat:planFormat}}:{}),
        ...(mode==='extract'?{text:{format:{type:'json_schema',name:'question_extraction',strict:true,schema:{type:'object',properties:Object.fromEntries(extractionFields.map(field=>[field,{type:'string'}])),required:extractionFields,additionalProperties:false}}}}:{}),
        ...(!reasoning?{temperature:0.3}:{reasoning:{effort:'medium'}}),
        max_output_tokens:reasoning?8192:common?500:mode==='summary'?1600:4096 }, { signal });
      let complete = false, extractionJson='';
      for await (const event of stream) {
        if (event.type === 'response.output_text.delta') {if(mode==='extract')extractionJson+=event.delta;else yield { delta:event.delta };}
        if (event.type === 'response.refusal.delta') yield { delta:event.delta };
        if (event.type === 'response.completed') { complete = true; yield { usage:event.response.usage }; }
        if (['response.failed','response.incomplete','error'].includes(event.type)) throw new Error('The answer could not be completed. Please try a shorter question.');
      }
      if (!complete) throw new Error('The answer stream ended before completion. Please try again.');
      if(mode==='extract'){
        let extracted;try{extracted=JSON.parse(extractionJson);}catch{throw new Error('Could not read this image. Please upload a clearer photo or type the question.');}
        if(extractionFields.some(field=>typeof extracted[field]!=='string'))throw new Error('Image extraction was incomplete. Please try a clearer photo.');
        yield {delta:extractionFields.map(field=>`${field}: ${extracted[field]}`).join('\n')};
      }
    }
  };
}
