import React, { useEffect, useRef, useState } from 'react';
import { io } from 'socket.io-client';
import { ArrowUp, ArrowRight, BookOpen, Check, ChevronRight, CircleHelp, Copy, ImagePlus, KeyRound, LayoutDashboard, LogOut, MessageCircle, Plus, RefreshCw, ShieldCheck, Sparkles, Square, Trash2, X, Zap } from 'lucide-react';
import { MathMarkdown } from './MathMarkdown.jsx';
import { GuidedAnswer } from './GuidedAnswer.jsx';

const samples=[{subject:'MATHEMATICS',title:'Make sense of quadratics',question:'Solve x² − 5x + 6 = 0 and explain each step.',symbol:'x²',tone:'purple'}, {subject:'PHYSICS',title:'Understand the why',question:'Why do objects of different masses fall with the same acceleration in a vacuum?',symbol:'↗',tone:'orange'}, {subject:'CHEMISTRY',title:'Find the right balance',question:'Balance the chemical equation Fe + O₂ → Fe₂O₃ and explain the method.',symbol:'H₂',tone:'green'}];
function Brand(){return <a className="brand" href="/"><span className="brand-icon"><Sparkles size={22}/></span>doubtbuddy<span className="brand-dot">.</span></a>;}
function CopyButton({value,label='Copy'}){const [copied,setCopied]=useState(false);return <button className="button subtle small" onClick={async()=>{try{await navigator.clipboard.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),1800);}catch{setCopied(false);}}}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Copied':label}</button>;}
export function App(){return location.pathname.startsWith('/admin')?<Admin/>:<Solver/>;}

function Solver(){
  const [credential,setCredential]=useState(''),[keyInput,setKeyInput]=useState(''),[loginBusy,setLoginBusy]=useState(false);
  const [status,setStatus]=useState('Disconnected'),[partner,setPartner]=useState(null),[demo,setDemo]=useState(false),[error,setError]=useState('');
  const [question,setQuestion]=useState(''),[attachment,setAttachment]=useState(null),[messages,setMessages]=useState([]),[busy,setBusy]=useState(false),[suggestions,setSuggestions]=useState([]),[tab,setTab]=useState('text');
  const [selectedStep,setSelectedStep]=useState(null),[extractedText,setExtractedText]=useState(''),[extracting,setExtracting]=useState(false);
  const [profile,setProfile]=useState({classLevel:'',examTarget:'',language:'',difficulty:'auto'});
  const questionRef=useRef(null);
  const [activeQuestion,setActiveQuestion]=useState(null);
  const socket=useRef(null),answerId=useRef(null),busyRef=useRef(false),fileRef=useRef(null),endRef=useRef(null),initial=useRef(false),lastStep=useRef('');
  const setWorking=value=>{busyRef.current=value;setBusy(value);};
  async function authenticate(key){
    setLoginBusy(true);setError('');
    try{const response=await fetch('/api/session',{method:'POST',headers:{Authorization:`Bearer ${key}`}});const data=await response.json();if(!response.ok)throw new Error(data.error);setCredential(data.token);setKeyInput('');}
    catch(e){setError(e.message);}finally{setLoginBusy(false);}
  }
  useEffect(()=>{
    if(initial.current)return;initial.current=true;
    const url=new URL(location.href);const key=url.searchParams.get('key');
    if(key){url.searchParams.delete('key');history.replaceState(null,'',url.pathname+url.search+url.hash);void authenticate(key);}
  },[]);
  useEffect(()=>{
    if(!credential)return;
    const s=io('/doubtBuddyLLM',{transports:['polling','websocket'],auth:{token:credential},reconnectionAttempts:5,reconnectionDelay:1000});socket.current=s;setStatus('Connecting');
    s.on('login-success',p=>{setPartner(p.partner);setDemo(p.demo);setStatus('Connected');setError('');});
    s.on('connect_error',e=>{setStatus('Disconnected');setError(e.message);setWorking(false);});
    s.on('disconnect',()=>{setStatus('Disconnected');setActiveQuestion(null);setWorking(false);setExtracting(false);setSelectedStep(null);answerId.current=null;setMessages(m=>m.map(x=>x.pending?{...x,pending:false,incomplete:true}:x));});
    s.on('processing-status',p=>{if(p.status==='Processing...')setWorking(true);});
    s.on('query-update-solution',p=>{const id=answerId.current;if(id)setMessages(m=>m.map(x=>x.id===id?{...x,content:x.content+p.chunk}:x));});
    s.on('query-response-solution',p=>{
      if(p.code==='BUSY'){setError(p.content);return;}
      const id=answerId.current;
      if(p.error){setError(p.content);setMessages(m=>m.map(x=>x.id===id?{...x,pending:false,incomplete:true}:x));}
      else if(p.kind!=='common'&&p.kind!=='extract'){
        lastStep.current=p.content;
        if(p.stage==='understanding')setActiveQuestion(p.questionId);
        setMessages(m=>m.map(x=>x.id===id?{...x,content:p.content,pending:false,answerId:p.requestId,stage:p.stage,data:p.data,questionId:p.questionId}:x));
      }
      answerId.current=null;setWorking(false);setExtracting(false);
    });
    s.on('common-question-solution',p=>setSuggestions(p.commonSolution));
    s.on('image-extraction-result',p=>setExtractedText(p.content));
    return()=>{s.disconnect();socket.current=null;};
  },[credential]);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth',block:'end'});},[messages.length,busy]);
  function submit(text=question,isFollowup=false){
    if(busyRef.current||status!=='Connected'||(!text.trim()&&!attachment))return;
    const id=crypto.randomUUID();answerId.current=id;setWorking(true);setError('');setSuggestions([]);
    setMessages(m=>[...m,{id:crypto.randomUUID(),role:'user',content:attachment?(text.trim()||'Solve the question in this image.'):text,image:attachment?.data},{id,role:'assistant',content:'',pending:true}]);
    if(attachment)socket.current.emit('image-query',{fileContent:attachment.data,fileName:attachment.name,textQuestion:text.trim(),extractedText,profile});
    else if(isFollowup)socket.current.emit('followup-query',[{step:(selectedStep?.content||lastStep.current).slice(0,24000),question:text,profile,...(selectedStep?{step_number:selectedStep.step_number,step_title:selectedStep.step_title,answer_id:selectedStep.answerId}: {})}]);
    else socket.current.emit('text-query',{textQuestion:text,profile});
    setQuestion('');setAttachment(null);setExtractedText('');setSelectedStep(null);
  }
  async function chooseImage(file){
    if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024){setError('Choose a PNG, JPEG, or WebP image smaller than 5 MB.');return;}
    const reader=new FileReader();reader.onload=()=>{setAttachment({name:file.name,data:reader.result});setExtractedText('');setSelectedStep(null);setError('');};reader.onerror=()=>setError('This image could not be read. Try selecting it again.');reader.readAsDataURL(file);
  }
  function reset(){if(busyRef.current)return;setMessages([]);setActiveQuestion(null);setSuggestions([]);setError('');setQuestion('');setAttachment(null);setExtractedText('');setSelectedStep(null);lastStep.current='';socket.current?.emit('reset-conversation');}
  function askStep(step,message){setSelectedStep({...step,answerId:message.answerId,content:message.content});setTab('text');setAttachment(null);setExtractedText('');setQuestion('');setTimeout(()=>{questionRef.current?.focus();questionRef.current?.scrollIntoView({behavior:'smooth',block:'center'});},0);}
  function extractImage(){if(!attachment||busyRef.current||status!=='Connected')return;setWorking(true);setExtracting(true);setError('');socket.current.emit('image-extract',{fileContent:attachment.data,fileName:attachment.name,textQuestion:question,profile});}
  function requestAction(event,message){if(busyRef.current||status!=='Connected')return;const id=crypto.randomUUID();answerId.current=id;setWorking(true);setError('');setMessages(m=>[...m,{id,role:'assistant',content:'',pending:true}]);socket.current.emit(event,{questionId:message.questionId});}
  return <div className="app-shell">
    <aside className="sidebar"><Brand/><div className="workspace-label">YOUR LEARNING SPACE</div><button className="nav-item active" onClick={reset}><MessageCircle size={18}/> Ask a doubt <Plus size={16} className="push"/></button><div className="sidebar-note"><BookOpen size={18}/><div><strong>A little clearer, every day.</strong><p>One question is all it takes to get started.</p></div></div><div className="sidebar-bottom"><a className="nav-item" href="/admin"><LayoutDashboard size={18}/> Partner console <ChevronRight size={15} className="push"/></a><div className="powered"><span className="mini-logo">∞</span><span>Built for curious minds<br/><strong>Doubtbuddy for enterprise</strong></span></div></div></aside>
    <main className="main"><header className="topbar"><span>Learning studio <span className="slash">/</span> <strong>Ask a doubt</strong></span><div className="header-right"><span className={`connection ${status==='Connected'?'online':''}`}><i/>{status==='Connected'?(partner?.name||'Connected'):status}</span><span className="avatar">{partner?.name?.slice(0,1).toUpperCase()||'D'}</span></div></header>
      <div className={`studio ${messages.length?'has-messages':''}`}>
        {demo&&<div className="notice demo"><Zap size={16}/> Demo mode: responses show a fixed example. Live AI is not enabled.</div>}
        <details className="learning-preferences"><summary>Learning preferences <span>Class, exam and language</span></summary><div className="profile-fields">
          <label>Class<select aria-label="Class" disabled={busy} value={profile.classLevel} onChange={e=>setProfile(p=>({...p,classLevel:e.target.value}))}><option value="">Infer from question</option>{Array.from({length:12},(_,i)=><option key={i} value={`Class ${i+1}`}>Class {i+1}</option>)}</select></label>
          <label>Exam target<select aria-label="Exam target" disabled={busy} value={profile.examTarget} onChange={e=>setProfile(p=>({...p,examTarget:e.target.value}))}>{['','School','JEE Main','JEE Advanced','NEET'].map(x=><option key={x} value={x}>{x||'Infer from question'}</option>)}</select></label>
          <label>Language for images or equations<input aria-label="Preferred language" list="languages" placeholder="Match my question" maxLength={60} disabled={busy} value={profile.language} onChange={e=>setProfile(p=>({...p,language:e.target.value}))}/><datalist id="languages">{['English','Hindi','Malayalam','Tamil','Telugu','Kannada','Bengali','Marathi','Gujarati','Punjabi','Urdu','Hinglish'].map(x=><option key={x}>{x}</option>)}</datalist></label>
          <label>Problem difficulty<select aria-label="Problem difficulty" disabled={busy} value={profile.difficulty} onChange={e=>setProfile(p=>({...p,difficulty:e.target.value}))}><option value="auto">Automatic</option><option value="standard">Standard</option><option value="advanced">Advanced / hard numerical</option></select></label>
        </div></details>
        {!messages.length?<><div className="eyebrow"><span/> A SPACE FOR YOUR NEXT “AHA!”</div><h1>Big questions.<br/><span>Clear answers.</span></h1><p className="intro">Stuck on a problem? Let’s work through it together.<br/>Ask anything, or upload a photo of your question.</p>
        <div className="sample-grid">{samples.map(sample=><button key={sample.subject} className={`sample-card ${sample.tone}`} disabled={busy} onClick={()=>{setQuestion(sample.question);setTab('text');setAttachment(null);}}><span className="sample-symbol">{sample.symbol}</span><span className="sample-subject">{sample.subject}</span><strong>{sample.title}</strong><span className="sample-bottom">Try a question <ArrowRight size={16}/></span></button>)}</div></>:<div className="conversation"><div className="conversation-title"><span><Sparkles size={17}/> Let’s figure it out</span><button className="button subtle small" disabled={busy} onClick={reset}><Plus size={15}/> New question</button></div>{messages.map(message=><article key={message.id} className={`message ${message.role}`}><div className="message-heading">{message.role==='assistant'?<><span className="answer-mark"><Sparkles size={14}/></span>Doubtbuddy <span className="muted">· Step by step</span></>:<>Your question</>}{message.role==='assistant'&&message.content&&!message.pending&&<span className="push"><CopyButton value={message.content}/></span>}</div>{message.image&&<img className="question-image" src={message.image} alt="Uploaded question"/>}{message.data&&['understanding','step','all-steps','final-answer'].includes(message.stage)?<GuidedAnswer message={message} onAction={requestAction} onAskStep={askStep} disabled={busy||status!=='Connected'} activeQuestion={activeQuestion}/>:<MathMarkdown onAskStep={message.role==='assistant'&&!message.pending&&!message.incomplete?(step)=>askStep(step,message):undefined} disabled={busy||status!=='Connected'}>{message.content}</MathMarkdown>}{message.pending&&!message.content&&<div className="thinking"><span/><span/><span/> Working through your question</div>}{message.pending&&message.content&&<span className="stream-caret"/>}{message.incomplete&&<div className="incomplete">Answer incomplete. Please submit your question again.</div>}</article>)}<div ref={endRef}/>{!busy&&lastStep.current&&<div className="followups">{suggestions.length?suggestions.map(q=><button key={q} onClick={()=>submit(q,true)}>{q}<ArrowUp size={14}/></button>):<button onClick={()=>{if(busyRef.current)return;setWorking(true);setError('');socket.current?.emit('common-question-query',{step:lastStep.current});}} disabled={status!=='Connected'}><CircleHelp size={15}/> Explore related questions</button>}</div>}</div>}
        {error&&<div className="notice error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
        {status!=='Connected'&&<form className="access-card" onSubmit={e=>{e.preventDefault();void authenticate(keyInput);}}><div><KeyRound size={18}/><strong>Connect your learning space</strong></div><p>Use the access key shared by your institution.</p><div className="input-row"><input aria-label="Partner access key" type="password" placeholder="Enter your partner access key" value={keyInput} required onChange={e=>setKeyInput(e.target.value)} autoComplete="off"/><button className="button primary" disabled={loginBusy}>{loginBusy?'Connecting…':'Connect'}<ArrowRight size={16}/></button></div></form>}
        <div className="composer">{selectedStep&&<div className="selected-step"><span>Asking about Step {selectedStep.step_number}: <MathMarkdown inline>{selectedStep.step_title}</MathMarkdown></span><button aria-label="Clear selected step" onClick={()=>setSelectedStep(null)}><X size={15}/></button></div>}<div className="composer-tabs"><button className={tab==='text'?'selected':''} onClick={()=>{setTab('text');setAttachment(null);setExtractedText('');}} disabled={busy}><MessageCircle size={15}/> Type a question</button><button className={tab==='image'?'selected':''} onClick={()=>{setTab('image');setSelectedStep(null);}} disabled={busy}><ImagePlus size={16}/> Upload an image</button><span className="math-label">LaTeX supported <span>∑</span></span></div>
          {tab==='image'?<div className="image-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)void chooseImage(e.dataTransfer.files[0]);}}>{attachment?<div className="attachment"><img src={attachment.data} alt="Selected question"/><span>{attachment.name}</span><button onClick={()=>setAttachment(null)} aria-label="Remove image" disabled={busy}><X size={17}/></button></div>:<button disabled={busy} onClick={()=>fileRef.current.click()}><ImagePlus size={26}/><strong>Drop your question here, or browse</strong><span>PNG, JPEG, WebP · up to 5 MB</span></button>}</div>:<textarea ref={questionRef} aria-label="Your question" placeholder={messages.length?'What would you like to understand better?':'What would you like to understand today?'} value={question} maxLength={messages.length?4000:12000} disabled={busy} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();submit(question,messages.length>0);}}}/>}
          <input type="file" ref={fileRef} hidden accept="image/png,image/jpeg,image/webp" onChange={e=>{void chooseImage(e.target.files[0]);e.target.value='';}}/>
          {tab==='image'&&<textarea aria-label="Image instructions" placeholder="Optional: solve Q4, explain step 3, or tell us your class…" value={question} maxLength={12000} disabled={busy} onChange={e=>setQuestion(e.target.value)}/>}
          {tab==='image'&&attachment&&<div className="extraction-review"><button className="button subtle small" disabled={busy||status!=='Connected'} onClick={extractImage}>{extracting?'Reading image…':'Read image before solving'}</button><p>Optional for handwriting or unclear photos. Review and correct the extracted question before solving.</p>{extractedText&&<label>Extracted question and diagram details<textarea aria-label="Extracted question" value={extractedText} maxLength={24000} disabled={busy} onChange={e=>setExtractedText(e.target.value)}/></label>}</div>}
          <div className="composer-bottom"><span><ShieldCheck size={14}/> Your next step starts here</span>{busy?<button className="button primary" onClick={()=>socket.current?.emit('cancel-query')}><Square size={14}/> Stop</button>:<button className="button primary" disabled={status!=='Connected'||(!question.trim()&&!attachment)} onClick={()=>submit(question,messages.length>0)}>Solve my doubt <ArrowUp size={17}/></button>}</div>
        </div><p className="footnote">Made for understanding, one step at a time. Always check important answers.</p>
      </div><footer className="studio-footer"><span>Clarity is a conversation.</span><span><Sparkles size={13}/> Powered by Doubtbuddy</span></footer>
    </main>
  </div>;
}

function Admin(){
  const [token,setToken]=useState(''),[input,setInput]=useState(''),[partners,setPartners]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[demo,setDemo]=useState(false),[secret,setSecret]=useState(null),[confirm,setConfirm]=useState(null);
  const [form,setForm]=useState({name:'',dailyLimit:1000,rpm:30,origins:'',expiry:''});
  async function api(path,options={},key=token){const response=await fetch(`/api/admin${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${key}`}});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed.');return data;}
  async function load(key=token){const data=await api('/partners',{},key);setPartners(data.partners);setReady(data.ready);setDemo(data.demo);}
  async function action(fn){setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
  const update=(key,value)=>setForm(f=>({...f,[key]:value}));
  return <div className="admin-shell"><header className="admin-header"><Brand/><div><a href="/" className="button subtle"><MessageCircle size={16}/> Learning studio</a>{token&&<button className="button subtle" onClick={()=>{setToken('');setPartners([]);setSecret(null);}}><LogOut size={16}/> Sign out</button>}</div></header><main className="admin-main"><div className="eyebrow"><span/> PARTNER CONSOLE</div><h1>Your partners.<br/><span>One connected experience.</span></h1><p className="intro">Create access, manage usage, and bring clarity to every learner.</p>
    {error&&<div className="notice error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
    {!token?<form className="admin-login" onSubmit={e=>{e.preventDefault();void action(async()=>{await load(input);setToken(input);setInput('');});}}><div className="icon-box"><KeyRound/></div><h2>Administrator access</h2><p>Enter the administrator token from your server’s environment settings.</p><label>Administrator token<input type="password" value={input} onChange={e=>setInput(e.target.value)} required autoComplete="off"/></label><button className="button primary" disabled={busy}>{busy?'Signing in…':'Open partner console'}<ArrowRight size={17}/></button></form>:<>
    <div className="stats-grid"><div><span>PARTNERS</span><strong>{partners.length}</strong><p>{partners.filter(p=>p.active&&(!p.expiresAt||p.expiresAt>Date.now())).length} active access keys</p></div><div><span>REQUESTS TODAY</span><strong>{partners.reduce((n,p)=>n+p.requests,0).toLocaleString()}</strong><p>Across your partners · UTC</p></div><div><span>AI SERVICE</span><strong className="service-status">{demo?'Demo mode':ready?'Connected':'Needs setup'}</strong><p>{demo?'Fixed example responses':ready?'OpenAI configured':'Add OPENAI_API_KEY to .env'}</p></div></div>
    {secret&&<section className="secret-card"><div className="section-heading"><h2><Check size={19}/> Access key created</h2><button className="button subtle small" onClick={()=>setSecret(null)}>Dismiss <X size={15}/></button></div><p>Copy these now. The full key is shown only once. Anyone with this link can use this partner’s allowance.</p><label>Partner API key</label><div className="secret-row"><code>{secret.apiKey}</code><CopyButton value={secret.apiKey}/></div><label>Shareable learning URL</label><div className="secret-row"><code>{secret.url}</code><CopyButton value={secret.url}/></div><a href={secret.url} target="_blank" rel="noreferrer" className="button primary small">Open learning studio <ArrowRight size={15}/></a></section>}
    <div className="admin-grid"><section className="panel"><div className="section-heading"><h2><Plus size={19}/> Add a partner</h2></div><form className="partner-form" onSubmit={e=>{e.preventDefault();void action(async()=>{const data=await api('/partners',{method:'POST',body:JSON.stringify({name:form.name,dailyLimit:Number(form.dailyLimit),rpm:Number(form.rpm),origins:form.origins.split(',').map(s=>s.trim()).filter(Boolean),...(form.expiry?{expiresAt:new Date(form.expiry).getTime()}: {})})});setSecret(data);setForm({name:'',dailyLimit:1000,rpm:30,origins:'',expiry:''});await load();});}}><label>Partner name<input required minLength={2} maxLength={100} placeholder="e.g. Infinity Learn" value={form.name} onChange={e=>update('name',e.target.value)}/></label><div className="two-columns"><label>Requests / day<input type="number" min={1} max={1000000} required value={form.dailyLimit} onChange={e=>update('dailyLimit',e.target.value)}/></label><label>Requests / minute<input type="number" min={1} max={1000} required value={form.rpm} onChange={e=>update('rpm',e.target.value)}/></label></div><label>Additional website origins <span>Optional</span><input placeholder="https://learn.example.com" value={form.origins} onChange={e=>update('origins',e.target.value)}/><small>Comma-separated origins for your partner’s own frontend.</small></label><label>Access expiry <span>Optional</span><input type="datetime-local" value={form.expiry} onChange={e=>update('expiry',e.target.value)}/></label><button className="button primary" disabled={busy}><KeyRound size={16}/> Generate partner key</button></form></section>
    <section className="panel partner-list"><div className="section-heading"><h2>Partner access</h2><button className="button subtle small" disabled={busy} onClick={()=>void action(()=>load())}><RefreshCw size={14}/> Refresh</button></div>{partners.length?<div className="table-wrap"><table><thead><tr><th>Partner</th><th>Usage today</th><th>Access</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{partners.map(p=><tr key={p.id}><td><strong>{p.name}</strong><code>{p.prefix}…</code></td><td><strong>{p.requests.toLocaleString()} <span className="muted">/ {p.dailyLimit.toLocaleString()}</span></strong><div className="usage-track"><i style={{width:`${Math.min(100,p.requests/p.dailyLimit*100)}%`}}/></div><small>{p.tokens.toLocaleString()} tokens</small></td><td><span className={`badge ${p.active&&(!p.expiresAt||p.expiresAt>Date.now())?'green':'gray'}`}>{!p.active?'Revoked':p.expiresAt&&p.expiresAt<=Date.now()?'Expired':'Active'}</span></td><td><div className="row-actions"><button title="Rotate key" aria-label={`Rotate ${p.name} key`} disabled={busy} onClick={()=>setConfirm({type:'rotate',partner:p})}><RefreshCw size={16}/></button><button title="Revoke key" aria-label={`Revoke ${p.name} key`} disabled={busy||!p.active} onClick={()=>setConfirm({type:'revoke',partner:p})}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>:<div className="empty-partners"><ShieldCheck size={32}/><h3>A fresh start for your partners</h3><p>Create your first partner to issue a key and a learning URL.</p></div>}</section></div>
    <section className="integration-note"><ShieldCheck size={20}/><div><strong>Built around your integration</strong><p>Use Socket.IO at <code>/doubtBuddyLLM</code> with the events in your implementation workbook. Your OpenAI key stays on the server. Partner keys can be exchanged for one-hour browser sessions at <code>POST /api/session</code>.</p></div></section>
    </>}
    </main>{confirm&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><h2 id="confirm-title">{confirm.type==='rotate'?'Rotate':'Revoke'} {confirm.partner.name}’s key?</h2><p>{confirm.type==='rotate'?'The existing key and sessions will stop working. You will receive a new key and URL.':'This will immediately disconnect this partner and disable their key and sessions.'}</p><div><button className="button subtle" onClick={()=>setConfirm(null)}>Cancel</button><button className="button primary" disabled={busy} onClick={()=>void action(async()=>{if(confirm.type==='rotate')setSecret(await api(`/partners/${confirm.partner.id}/rotate`,{method:'POST'}));else await api(`/partners/${confirm.partner.id}`,{method:'DELETE'});setConfirm(null);await load();})}>{confirm.type==='rotate'?'Rotate key':'Revoke access'}</button></div></section></div>}</div>;
}
